// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Searchera.Models;

public partial class Application
{
    public int Id { get; set; }
    [Required(ErrorMessage = "The Resume Link is Required!")]
    public string ResumeLink { get; set; }
    [Required(ErrorMessage ="The Cover Letter is Required!")]
    [MaxLength(500,ErrorMessage ="This is Long Letter!")]
    [MinLength(50, ErrorMessage = "This is Small Letter!")]
    public string CoverLetter { get; set; }
    [ForeignKey("Job")]
    [Required(ErrorMessage = "Choose Job Title")]
    public int JobID { get; set; }
    [ForeignKey("User")]
    [Required(ErrorMessage = "Choose The User")]
    public int UserId { get; set; }

    public virtual JobListing? Job { get; set; }

    public virtual User? User { get; set; }
}