// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Searchera.Models;

public partial class User
{
    public int Id { get; set; }
    [Required(ErrorMessage = "The Name id Required!")]
    [MaxLength(70, ErrorMessage = "The Max Length of Name is 70!")]
    [MinLength(3, ErrorMessage = "The Min Length of Name is 3!")]
    public string Name { get; set; }
    [Required(ErrorMessage = "The Email is Required!")]
    [EmailAddress(ErrorMessage = "wrong in Email!")]
    public string Email { get; set; }
    [Required(ErrorMessage = "The Password is Required!")]
    [DataType(DataType.Password, ErrorMessage = "it is wrong password!")]
    public string Password { get; set; }
    public string ProfileImage { get; set; }
    [NotMapped]
    public IFormFile ProfileImageFile { get; set; }
    public string Role { get; set; }
    [NotMapped]
    [Required(ErrorMessage ="Choose your role!")]
    public int RoleID { get; set; }

    public virtual ICollection<Application> Applications { get; set; } = new List<Application>();

    public virtual ICollection<Company> Companies { get; set; } = new List<Company>();

    public virtual ICollection<JobListing> JobListings { get; set; } = new List<JobListing>();

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();
}